### ISSUE TITLE
Alfresco-value-assistance-repo does not work cause solr exceptions are thrown

### ISSUE THREAD

**Issue by zhasik92** [dgcloud/alfresco-value-assistance#6]
Hi!

I'm trying to test your addon.  
I'm working on windows.

I've tryed to run.bat, but following exceptions are thrown: 
`2016-11-07 13:31:29,298  ERROR [solr.core.CoreContainer] [coreLoadExecutor-5-thread-1] Unable to create core: collection1
 org.apache.solr.common.SolrException: Could not load core configuration for core collection1
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:554)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:261)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:253)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error loading solr config from D:\\alfrescoExamples\\alfresco-value-assistance-forked\\alfresco-value-assistance-master\\alfresco-value-assistance-repo/alf_data_dev/solr4/config/collection1\solrconfig.xml
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:148)
	at org.apache.solr.core.ConfigSetService.createSolrConfig(ConfigSetService.java:79)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:61)
	... 9 more
Caused by: java.io.IOException: Can't find resource 'solrconfig.xml' in classpath or 'D:\alfrescoExamples\alfresco-value-assistance-forked\alfresco-value-assistance-master\alfresco-value-assistance-repo\alf_data_dev\solr4\config\collection1\conf'
	at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:362)
	at org.apache.solr.core.SolrResourceLoader.openConfig(SolrResourceLoader.java:308)
	at org.apache.solr.core.Config.<init>(Config.java:116)
	at org.apache.solr.core.Config.<init>(Config.java:86)
	at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:161)
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:144)
	... 11 more
2016-11-07 13:31:29,307  ERROR [solr.core.CoreContainer] [coreLoadExecutor-5-thread-1] null:org.apache.solr.common.SolrException: Unable to create core: collection1
	at org.apache.solr.core.CoreContainer.recordAndThrow(CoreContainer.java:911)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:568)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:261)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:253)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Could not load core configuration for core collection1
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:554)
	... 8 more
Caused by: org.apache.solr.common.SolrException: Error loading solr config from D:\\alfrescoExamples\\alfresco-value-assistance-forked\\alfresco-value-assistance-master\\alfresco-value-assistance-repo/alf_data_dev/solr4/config/collection1\solrconfig.xml
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:148)
	at org.apache.solr.core.ConfigSetService.createSolrConfig(ConfigSetService.java:79)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:61)
	... 9 more
Caused by: java.io.IOException: Can't find resource 'solrconfig.xml' in classpath or 'D:\alfrescoExamples\alfresco-value-assistance-forked\alfresco-value-assistance-master\alfresco-value-assistance-repo\alf_data_dev\solr4\config\collection1\conf'
	at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:362)
	at org.apache.solr.core.SolrResourceLoader.openConfig(SolrResourceLoader.java:308)
	at org.apache.solr.core.Config.<init>(Config.java:116)
	at org.apache.solr.core.Config.<init>(Config.java:86)
	at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:161)
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:144)
	... 11 more
`

Could you help me?

**Comment by douglascrp** [comment]
I haven't seen that error before.

**Comment by zhasik92** [comment]
Thank you.
I've tested it on server, it works fine, but I've failed to run it in dev environment with embedded tomcat server.

**Comment by douglascrp** [comment]
@zhasik92 Same error?

**Comment by zhasik92** [comment]
yes. I run it  using run.sh, but I'm using it without spring-loaded.

**Comment by douglascrp** [comment]
@zhasik92 Is this still an issue with the current version available here?
Can you let me know if it is working for you?

If it is not a problem anymore, then I am going to close this one.

**Comment by douglascrp** [comment]
As there is no answer from the reporter, I am closing it.
